# Generated by Django 3.1.12 on 2022-11-10 13:39

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import ino_v3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Avatar', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Avatar', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=16)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Instagram', models.CharField(max_length=100)),
                ('Twitter', models.CharField(max_length=100)),
                ('Github', models.CharField(max_length=100)),
                ('LinkedIn', models.CharField(max_length=100)),
                ('Portfolio', models.CharField(max_length=100)),
                ('Other', models.CharField(max_length=100)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ino_v3.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=20)),
                ('ProjectImage', models.CharField(max_length=50)),
                ('Url', models.CharField(max_length=50)),
                ('Technology', djongo.models.fields.ArrayField(model_container=ino_v3.models.Tech, model_form_class=ino_v3.models.TechForm)),
                ('Description', models.CharField(max_length=100)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ino_v3.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Followed', djongo.models.fields.ArrayField(model_container=ino_v3.models.Follow, model_form_class=ino_v3.models.FollowForm)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ino_v3.signup')),
            ],
        ),
    ]
